openapi: 3.0.0
info:
  title: SpyneAI-assignment
  version: 1.0.0
  description: API documentation for SpyneAI assignment
servers:
  - url: http://127.0.0.1:8000
    description: Local development server

paths:
  /api/v1/auth/register:
    post:
      summary: Register a new user
      description: Register a new user with name, email, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: test2
                email:
                  type: string
                  format: email
                  example: test2@mail.com
                password:
                  type: string
                  example: test2
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        example: test2
                      email:
                        type: string
                        example: test2@mail.com
                      password:
                        type: string
                        example: $2b$10$AEzb5A/bAu5G6lx57QIrX.OuVM9KtfDi/KwL2rju.cYPQK3RoVUZG
                      _id:
                        type: string
                        example: 6798dee952bb3b3e50e6d2d3
                      __v:
                        type: integer
                        example: 0
        "409":
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Email already exists

  /api/v1/auth/login:
    post:
      summary: Login a user
      description: Login a user with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: test@mail.com
                password:
                  type: string
                  example: test
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: 6798da69424835c19e96accb
                      name:
                        type: string
                        example: test
                      email:
                        type: string
                        example: test@mail.com
                      password:
                        type: string
                        example: $2b$10$2vwBnw6nikwHUAJyRY2I5efdxR9tcsaMazsjHb8p1CuT629P/Dxdi
                      __v:
                        type: integer
                        example: 0
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Invalid Credentials
